services:
  web:
    image: ayodelefestung/mydjangoapp:v2
    restart: unless-stopped
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static_root
      - media_volume:/app/media
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  static_volume:
  media_volume:
  redis_data:
